version: '2.2'

services:
  aida:
    image: aida:prod
    environment:
      PG_HOST: ec2-54-247-125-38.eu-west-1.compute.amazonaws.com
      PG_PORT: 5432
      PG_USER: dgwxoyycemhser
      PG_PASSWORD: 5b5e033466da50e55fc75e8b3b0badb2a103bcb85906f856c28b69bde1f0a8c2
      PG_DB: d4jvcfg26vd6d
      DATABASE_URL: postgres://dgwxoyycemhser:5b5e033466da50e55fc75e8b3b0badb2a103bcb85906f856c28b69bde1f0a8c2@ec2-54-247-125-38.eu-west-1.compute.amazonaws.com:5432/d4jvcfg26vd6d
    build: 
      context: .
    container_name: aida
    restart: always
    volumes: 
      - .:/app
    ports:
      - "80:3000"
    depends_on:
      - postgres
    networks: 
      - aida-network
  postgres:
    container_name: postgres-db
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "55432:5432"
    networks:
      - aida-network
    restart: unless-stopped

networks:
  aida-network:
    driver: bridge

volumes:
  postgres:
  pgadmin: