FROM node:8.9-alpine as dev
ENV NODE_ENV=development
WORKDIR /app/server
COPY ./server/package*.json ./
RUN npm install
WORKDIR /app/client
COPY ./client/package*.json ./
RUN npm install
WORKDIR /app
COPY . .
WORKDIR /app/server
EXPOSE 8080 3000
CMD ["npm", "run", "dev"]
